### ISSUE TITLE
Failing node merge

### ISSUE THREAD

**Issue by nissimsan** [transmute-industries/jsonld-to-cypher#3]
I'm attempting to import the same resource twice, as part of two separately generated/imported cypher scripts. 

I'm getting `Node(45) already exists with label `Resource` and property `uri` = 'did:key:z6Mkf8r9cUvN48fPhmi13FMgFDg6ccVqmt1spny4f2QoymDP'` which seems like unintended behavior. If the URI is the same, then the nodes should merge. But it seems like `MERGE` doesn't do the trick for some reason. 

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/34443212/199064157-7ae5a6f1-4bb1-4590-b13c-681d03372d8c.png">

**Comment by nissimsan** [comment]
Specifically, this is what causes the MERGE to fail:

`MERGE ( n1 :Resource { uri: "did:key:z6Mkf8r9cUvN48fPhmi13FMgFDg6ccVqmt1spny4f2QoymDP", location: "urn:uuid:5e45f155-c949-4005-a7e5-26ni58b6a59a:_:c14n2" } )`

`MERGE ( n1 :Resource { uri: "did:key:z6Mkf8r9cUvN48fPhmi13FMgFDg6ccVqmt1spny4f2QoymDP", location: "did:key:z6MkfX5oKE8vuuftWn7mZJRZqpPTxGk9oK94gnCztcEkb7Vd:_:c14n1" } )`

**Comment by OR13** [comment]
hmm

**Comment by nissimsan** [comment]
Nice! Thanks
