### ISSUE TITLE
Introduce `term` keyword to simplify data model 

### ISSUE THREAD

**Issue by nissimsan** [transmute-industries/jsonld-to-cypher#5]
Continuing from https://github.com/transmute-industries/jsonld-to-cypher/issues/4...

I propose that the following JSON-LD: 

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471",
  "type": [
    "VerifiableCredential",
    "CommercialInvoiceCredential"
  ],
  "name": "Commercial Invoice Certificate",
  "issuanceDate": "2022-10-08T12:30:00Z",
  "issuer": {
    "type": [
      "Organization"
    ],
    "id": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
    "name": "Slovenian Steel",
    "description": "Melting and Pouring Steel"
  }
}
```

Could be both simpler and more precisely represented like this: 

```
MERGE ( n0 : Organization { id: "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn", description: "Melting and Pouring Steel", descriptionTerm: "https://schema.org/description", name: "Slovenian Steel", nameTerm: "https://schema.org/name" } )
MERGE ( n2 : OrganizationTerm { id: "https://schema.org/Organization"  } )
MERGE ( n5 : CommercialInvoiceCredentialTerm { id: "https://w3id.org/traceability#CommercialInvoiceCredential"  } )
MERGE ( n6 : VerifiableCredentialTerm { id: "https://www.w3.org/2018/credentials#VerifiableCredential"  } )
MERGE ( n9 : VerifiableCredential : CommercialInvoiceCredential { id: "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471" ,  name: "Commercial Invoice Certificate", nameTerm: "https://schema.org/name", issuanceDate: datetime("2022-10-08T12:30:00Z"), issuanceDateTerm: "https://www.w3.org/2018/credentials#issuanceDate" } )
MERGE (n0)-[e0: Type { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" } ]->(n2)
MERGE (n9)-[e5: Type { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" } ]->(n5)
MERGE (n9)-[e6: Type { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" } ]->(n6)
MERGE (n9)-[e7: Issuer { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://www.w3.org/2018/credentials#issuer" } ]->(n0)
RETURN n0,n2,n5,n6,n9
```

![image](https://user-images.githubusercontent.com/34443212/199781985-9ce31bb7-db46-4d0e-9282-353641a55a6f.png)

Specifically, I am introducing a `term` keyword which is used: 
1. For property definitions, for example for `name` and `nameTerm` 
2. For class definitions, which the `type` edges can point at, for example OrganizationTerm.

**Comment by nissimsan** [comment]
For reference, today the same JSON-LD becomes: 

```
MERGE ( n0 : DecentralizedIdentifier { id: "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn" ,  description: "Melting and Pouring Steel", name: "Slovenian Steel" } )
MERGE ( n1 : UniformResourceLocator { id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"  } )
MERGE ( n2 : UniformResourceLocator { id: "https://schema.org/Organization"  } )
MERGE ( n3 : UniformResourceLocator { id: "https://schema.org/description"  } )
MERGE ( n4 : UniformResourceLocator { id: "https://schema.org/name"  } )
MERGE ( n5 : UniformResourceLocator { id: "https://w3id.org/traceability#CommercialInvoiceCredential"  } )
MERGE ( n6 : UniformResourceLocator { id: "https://www.w3.org/2018/credentials#VerifiableCredential"  } )
MERGE ( n7 : UniformResourceLocator { id: "https://www.w3.org/2018/credentials#issuanceDate"  } )
MERGE ( n8 : UniformResourceLocator { id: "https://www.w3.org/2018/credentials#issuer"  } )
MERGE ( n9 : UniformResourceName { id: "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471" ,  name: "Commercial Invoice Certificate", issuanceDate: datetime("2022-10-08T12:30:00Z") } )
MERGE (n0)-[e0: Type { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" } ]->(n2)
MERGE (n3)-[e1: Predicate { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedPredicate" } ]->(n0)
MERGE (n4)-[e2: Predicate { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedPredicate" } ]->(n0)
MERGE (n4)-[e3: Predicate { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedPredicate" } ]->(n9)
MERGE (n7)-[e4: Predicate { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedPredicate" } ]->(n9)
MERGE (n9)-[e5: Type { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" } ]->(n5)
MERGE (n9)-[e6: Type { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" } ]->(n6)
MERGE (n9)-[e7: Issuer { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://www.w3.org/2018/credentials#issuer" } ]->(n0)
MERGE (n9)-[e8: Relationship { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedRelationship" } ]->(n1)
MERGE (n9)-[e9: Relationship { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedRelationship" } ]->(n3)
MERGE (n9)-[e10: Relationship { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedRelationship" } ]->(n8)
RETURN n0,n1,n2,n3,n4,n5,n6,n7,n8,n9
```

![image](https://user-images.githubusercontent.com/34443212/199784029-acca8159-4f9c-4523-a71a-4c5c324d148f.png)

Which is very verbose, and where the Predicate edges are imprecise (see #4) and Relationship edges doesn't really seem to do anything.

**Comment by OR13** [comment]
Some of the "Predicate" edges like `https://vocabulary.transmute.industries/ns/dynamic/#disclosedRelationship` are added automatically, to ensure the graph is connected.

Others could be "converted" to a string label, from an IRI... but that conversion encodes some intention... for example, how useful would "DisclosedRelationship" really be vs "Predicate"?

**Comment by nissimsan** [comment]
The "Predicate" edges are problematic because they connect to Nodes, not Properties (#4). For example 
```
MERGE (n4)-[e3: Predicate { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedPredicate" } ]->(n9)
MERGE (n7)-[e4: Predicate { id : "urn:uuid:a8e3cd1f-8e13-4630-b0f9-6dbaf9112471", predicate: "https://vocabulary.transmute.industries/ns/dynamic/#disclosedPredicate" } ]->(n9)
```
connect the `VC` node to the `schema.org/name` and `schema.org/description` nodes. But it does _not_ connect `VC.name` to `schema.org/name` and `VC.description` to `schema.org/description`... So it's really just saying "one of these properties is schema.org/name". You'll have to guess which one - which seems rather pointless.

Instinctively I would want a dedicated node for, say, `https://schema.org/name` too. But if it can't be connected to the precise property where it is used, rather than ensuring they're connected, I rather question it the node makes sense at all. 

I looked a bit at the [Neosemantics configuration](https://youtu.be/LO-OvQaBq8s?t=1216) for inspiration and there is clearly not one right way to do this. I considered going full-on RDF (akin to n10s `KEEP` option) and drop the replace the JSON name for the corresponding JSON-LD term. 
But Neo4j wouldn't accept `MERGE ( n9 : UniformResourceName {  https://schema.org/name: "Commercial Invoice Certificate" } )`. 

But with a convention that any `property` also has a corresponding `propertyTerm` we can maintain all information (ability to regenerate both RDF and JSON). The example would be: 
`MERGE ( n9 : UniformResourceName {   name: "Commercial Invoice Certificate", nameTerm: "https://schema.org/name" } )`. 

Do I like inventing convention? No. Do I like repeating terms more than once? No. But if my assessment of the trade off holds true, then I'd find this a preferable model. 

(I'm also proposing slightly different node labels, but let's save that for later)

**Comment by nissimsan** [comment]
This issue was useful earlier for me to remember my initial investigations. The transformation has changed a fair bit since then, though, and we are collaborating on next steps in jira. We're also going a bit beyond what I am suggesting here with a `term` property, instead basing the graph id on full URIs. 
Closing this as outdated...
